In [1]:
import tensorflow as tf

print(tf.__version__)
a=tf.random.uniform([2,3],0,1)
print(a)
print(type(a))

2.9.2
tf.Tensor(
[[0.29681087 0.9672046  0.5554061 ]
 [0.13630223 0.6088182  0.40402234]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
import tensorflow as tf
import numpy as np

t=tf.random.uniform([2,3],0,1)
n=np.random.uniform(0,1,[2,3])
print("tensorflow로 생성한 텐서:\n",t,"\n")
print("numpy로 생성한 ndarray:\n",n,"\n")

res=t+n # 텐서 t와 ndarray n의 덧셈
print("덧셈 결과:\n",res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.9432001  0.26920402 0.83036816]
 [0.12434483 0.24369621 0.8969513 ]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[1.01895191e-01 6.36281586e-02 4.35449320e-01]
 [9.76895098e-01 4.53285268e-02 9.43699737e-04]] 

덧셈 결과:
 tf.Tensor(
[[1.0450953  0.3328322  1.2658175 ]
 [1.1012399  0.28902474 0.89789504]], shape=(2, 3), dtype=float32)


In [4]:
import tensorflow as tf
import tensorflow.keras.datasets as ds

# MNIST 읽고 텐서 모양 출력
(x_train, y_train),(x_test, y_test)=ds.mnist.load_data()
yy_train=tf.one_hot(y_train,10,dtype=tf.int8) # 원핫 코드로 변환
print("MNIST: ",x_train.shape,y_train.shape,yy_train.shape)

# CIFAR-10 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.cifar10.load_data()
yy_train=tf.one_hot(y_train,10,dtype=tf.int8)
print("CIFAR-10: ",x_train.shape,y_train.shape,yy_train.shape)
# Boston Housing 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.boston_housing.load_data()
print("Boston Housing: ",x_train.shape,y_train.shape)

# Reuters 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.reuters.load_data()
print("Reuters: ",x_train.shape,y_train.shape)

11490434/11490434 [==============================] - 0s 0us/step
MNIST:  (60000, 28, 28) (60000,) (60000, 10)
170498071/170498071 [==============================] - 3s 0us/step
CIFAR-10:  (50000, 32, 32, 3) (50000, 1) (50000, 1, 10)
57026/57026 [==============================] - 0s 0us/step
Boston Housing:  (404, 13) (404,)
2110848/2110848 [==============================] - 0s 0us/step
Reuters:  (8982,) (8982,)
