파이썬을 사용하면 쉽게 데이터 분석 가능
목적에 맞는 패키지를 설치하면 더 쉽게 데이터 분석 가능
필요한 패키지를 pip 명령어로 설치 가능.

# 넘파이로 배열 다루기

- 넘파이는 배열과 행렬을 쉽게 사용하게 해주는 패키지
- 속도가 매우 빠르고 응용이 쉬움

In [3]:
import numpy as np
a = np.array([[2,3],[5,2]])
print(a)

[[2 3]
 [5 2]]


In [5]:
d = np.array([[1,2,3,4,5],[2,4,6,8,10],[5,6,7,8,9]])
print(d)

#배열 슬라이싱 하기

print(d[1][2])
print(d[1,2])
print(d[1:,3:])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5  6  7  8  9]]
6
6
[[ 8 10]
 [ 8  9]]


In [9]:
#배열의 크기 알아내기:shape
# 배열의 행과 열을 튜플로 반환

d = np.array([2,3,4,5,6])
print(d.shape)

e = np.array([[1,2,3,4],[3,4,5,6]])
print(e.shape)

(5,)
(2, 4)


In [ ]:
#배열 유형 바꾸기 : astype()

In [14]:
data = np.arange(1,5)
print(data.dtype)
data = data.astype('float64')
print(data)


int64
[1. 2. 3. 4.]


In [ ]:
#1로 이뤄진 배열 만들기 : np.arange() 2이상 10미만 원소로 이뤄진 배열 생성

In [19]:
print(np.zeros((1,5)))
print(np.ones((2,3)))

[[0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#행과 열 바꾸기 : np.transpose()
a = np.ones((2,3)) 
print(a)
b = np.transpose(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
#배열의 사칙 연산
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[12,23,14],[36,47,58]])
arr3 = np.array([100,200,300])

arr1+arr3

#크기가 서로 같아야지 사칙 연산 가능.


array([[102, 203, 304],
       [106, 207, 308]])